// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnqIjTdRqOodUtrpolrP-xiqflUMlYB7k',
    appId: '1:26203121839:web:901b11a7feabc05c2b0c5a',
    messagingSenderId: '26203121839',
    projectId: 'food-delievery-app-f16e2',
    authDomain: 'food-delievery-app-f16e2.firebaseapp.com',
    storageBucket: 'food-delievery-app-f16e2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmYeMFs-RC2q9JXqYzhz3dJH-lF4h0Mac',
    appId: '1:26203121839:android:7bf60846c144f1402b0c5a',
    messagingSenderId: '26203121839',
    projectId: 'food-delievery-app-f16e2',
    storageBucket: 'food-delievery-app-f16e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChMM5i8SsmZxjM7S4lCiiXsgwJft-pB3c',
    appId: '1:26203121839:ios:226034650cb19c522b0c5a',
    messagingSenderId: '26203121839',
    projectId: 'food-delievery-app-f16e2',
    storageBucket: 'food-delievery-app-f16e2.appspot.com',
    iosBundleId: 'com.example.foodDelieveryApp',
  );
}
